//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTellerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public int BMonthID { get; set; }
        public int FavColorID { get; set; }
        public int NumOfSibsID { get; set; }
    
        public virtual BMonth BMonth { get; set; }
        public virtual FavColor FavColor { get; set; }
        public virtual NumOfSib NumOfSib { get; set; }
    }
}
